openapi: 3.0.3
info:
  description: >-
    This is an example API specification.
  version: 1.0.0
  title: Example API
tags:
  - name: health
    description: Everything related to health checks, ping operations, ...

paths:
  /health:
    get:
      tags:
        - health
      summary: This is a single health check endpoint
      description: This endpoint will become active as soon as the application started.
      operationId: health
      responses:
        '200':
          description: operation succeeded, the service API is operational
          content:
            text/plain:
              schema:
                type: string
                example: ok
